### ISSUE TITLE
Bump avro.version from 1.11.3 to 1.12.0

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#13764] opened 2024-08-07 00:54 UTC
Check why the tests are failing in #13754

**Comment by abhioncbr** [comment] 2024-08-12 12:38
The issue is because of the newly introduced class [PrimitivesArrays.java](https://github.com/apache/avro/pull/2389/files#diff-902e4a96b065212aa56ec8b8d83c7031a219b5d0efe3c4deafe3b4f3e05ef70e) in avro. Here is the merged [PR](https://github.com/apache/avro/pull/2389) for reference. 

Also, more context in the linked [ticket](https://issues.apache.org/jira/browse/AVRO-2307).

because of this newly introduced class, the boxing/unboxing issue is happening for the primitives data type array.

**Comment by Jackie-Jiang** [comment] 2024-08-12 20:06
Thanks @abhioncbr for the investigation! Do you want to help fix it?

**Comment by abhioncbr** [comment] 2024-08-12 22:18
Sure, I can give it a try to fix the avro reader part. Thanks

**Comment by abhioncbr** [comment] 2024-09-03 09:48
We decided not to upgrade the version because of some reported issues with Avro primitive array support. closing this issue. Thanks

**Closed by abhioncbr** 2024-09-03 09:48 UTC
Labels: help wanted, dependencies
