### ISSUE TITLE
flaky test org.apache.pinot.controller.api.TableViewsTest.setUp

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#11783] opened 2023-10-11 06:48 UTC
https://github.com/apache/pinot/actions/runs/6478269923/job/17589792539?pr=11780
```
2023-10-11T05:42:25.8353888Z [ERROR] org.apache.pinot.controller.api.TableViewsTest.setUp -- Time elapsed: 7.787 s <<< FAILURE!
2023-10-11T05:42:25.8356154Z java.io.IOException: org.apache.pinot.common.exception.HttpErrorStatusException: Got error status code: 404 (Not Found) with reason: "Table not found" while sending request: http://localhost:18998/tables/viewsTable/externalview to controller: fv-az646-54.bnyr55kgab5uhfdhcgffazkscg.bx.internal.cloudapp.net, version: Unknown
2023-10-11T05:42:25.8357862Z 	at org.apache.pinot.controller.helix.ControllerTest.sendGetRequest(ControllerTest.java:786)
2023-10-11T05:42:25.8359072Z 	at org.apache.pinot.controller.helix.ControllerTest.sendGetRequest(ControllerTest.java:776)
2023-10-11T05:42:25.8359887Z 	at org.apache.pinot.controller.api.TableViewsTest.getTableView(TableViewsTest.java:175)
2023-10-11T05:42:25.8360926Z 	at org.apache.pinot.controller.api.TableViewsTest.setUp(TableViewsTest.java:91)
2023-10-11T05:42:25.8361656Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-10-11T05:42:25.8364335Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-10-11T05:42:25.8365253Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-10-11T05:42:25.8369257Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-10-11T05:42:25.8370085Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
2023-10-11T05:42:25.8371172Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
2023-10-11T05:42:25.8372186Z 	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
2023-10-11T05:42:25.8379518Z 	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
2023-10-11T05:42:25.8380429Z 	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
2023-10-11T05:42:25.8384477Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
2023-10-11T05:42:25.8385176Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2023-10-11T05:42:25.8385715Z 	at org.testng.TestRunner.privateRun(TestRunner.java:848)
2023-10-11T05:42:25.8386208Z 	at org.testng.TestRunner.run(TestRunner.java:621)
2023-10-11T05:42:25.8390188Z 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
2023-10-11T05:42:25.8390786Z 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
2023-10-11T05:42:25.8391349Z 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
2023-10-11T05:42:25.8391852Z 	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
2023-10-11T05:42:25.8394923Z 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
2023-10-11T05:42:25.8395535Z 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
2023-10-11T05:42:25.8396090Z 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
2023-10-11T05:42:25.8396639Z 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
2023-10-11T05:42:25.8400464Z 	at org.testng.TestNG.runSuites(TestNG.java:1114)
2023-10-11T05:42:25.8400920Z 	at org.testng.TestNG.run(TestNG.java:1082)
2023-10-11T05:42:25.8401510Z 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
2023-10-11T05:42:25.8402282Z 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
2023-10-11T05:42:25.8403067Z 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
2023-10-11T05:42:25.8403853Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2023-10-11T05:42:25.8404629Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2023-10-11T05:42:25.8405322Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
2023-10-11T05:42:25.8405998Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
2023-10-11T05:42:25.8408212Z Caused by: org.apache.pinot.common.exception.HttpErrorStatusException: Got error status code: 404 (Not Found) with reason: "Table not found" while sending request: http://localhost:18998/tables/viewsTable/externalview to controller: fv-az646-54.bnyr55kgab5uhfdhcgffazkscg.bx.internal.cloudapp.net, version: Unknown
2023-10-11T05:42:25.8409568Z 	at org.apache.pinot.common.utils.http.HttpClient.wrapAndThrowHttpException(HttpClient.java:448)
2023-10-11T05:42:25.8410449Z 	at org.apache.pinot.controller.helix.ControllerTest.sendGetRequest(ControllerTest.java:783)
2023-10-11T05:42:25.8410995Z 	... 33 more
2023-10-11T05:42:25.8411171Z 
```

**Comment by Jackie-Jiang** [comment] 2023-10-12 01:23
Duplicate of #11760, fixed with #11770

**Closed by Jackie-Jiang** 2023-10-12 01:23 UTC
Labels: flaky-test
