### ISSUE TITLE
Feature request: realtime table bouncing

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#151] opened 2016-06-04 06:30 UTC
Whenever I upgrade the schema of a table, I need to wait up to 1hour to wait for current segment to be persisted then next realtime segment will pick up the new schema. If I want this change to take immediately then I need to bounce all the realtime servers, which is not desired behavior since I'm running many tables on the same server.

For implementation, we can persist current in_progress segment then new created segment will just catch up with new schema.

**Comment by kishoreg** [comment] 2016-06-04 06:51
+1 for the feature. Are there any other alternatives other than forcing current segment to be flushed?

**Comment by rven1** [comment] 2016-06-04 06:59
+1 for the feature. It seems low cost to force the current segment to be
flushed. This would be an issue only if we upgrade the schema often, which
is not usual.

**Comment by fx19880617** [comment] 2016-06-04 07:06
The other alternative I can think of is to drop current in_progress segment then restart it.
For this, we need to reinit kafka consumer to make sure we are consuming from the offsets that previous segment committed.

**Comment by rven1** [comment] 2016-06-04 07:52
Wouldn't dropping the current segment cause queries to give inconsistent
results during the time that the realtime segment catches up? What is the
benefit in dropping the segment over just moving to a new segment? Aren't
previous segments still with the old schema?

**Comment by kishoreg** [comment] 2016-06-06 06:12
+1 to what jfim said. We need to make sure this works with new design as well.

**Comment by haibow** [comment] 2019-08-29 01:31
@mcvsubbu Thanks for your inputs!

In our environment, around 2/3 of our production tables are REALTIME, and we are seeing more and more requests to evolve schemas, especially with our recent efforts to onboard customers in a self-serve mode. 

Our flush thresholds are 5 hours by default, by which time the new schema should be picked up. But the problem is when to reload segments. If we reload segments right after the schema change (call reload endpoint in the onboarding portal when the user bumps the kafka schema version), the consuming segments would keep consuming and **seal with the old schema**. This results in schema mismatch at query time, causing this segment to be dropped, since this would be the only segment with the old schema - old segment are reloaded with the new schema, and new segments would pick up the new schema as well. Reloading segments X hours after the schema change could solve the issue, but it adds operational overhead.

So, if we can force flush the consuming segments upon schema change, once the new segments start consuming with the new schema, we can call reload endpoint on all old segments, which would both solve the schema mismatch issue, and allow consumption with the new schema right away.

If you anticipate issues with force flushing segments across partitions, we can manage customers' expectations on the time to pick up the new schema, and only address the schema mismatch issue, like upon completion of the consuming segment, fetch the latest schema and add the new column(s) to the mutable segment?

**Closed** 2024-09-24 18:41 UTC
