### ISSUE TITLE
Flaky Test: PulsarConsumerTest#testPartitionLevelConsumerBatchMessages

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#10597] opened 2023-04-12 22:27 UTC
Saw this in my PR: https://github.com/apache/pinot/actions/runs/4682800087/jobs/8297108045?pr=10596

```
Error:  org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest.testPartitionLevelConsumer  Time elapsed: 0.8 s  <<< FAILURE!
java.lang.AssertionError: expected [500] but found [99]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest.testPartitionLevelConsumer(PulsarConsumerTest.java:298)
...
```

Not sure who has context for this.

**Comment by Jackie-Jiang** [comment] 2023-04-13 00:03
cc @KKcorps

**Comment by Jackie-Jiang** [comment] 2023-11-14 18:25
Duplicate of #8537

**Closed by Jackie-Jiang** 2023-11-14 18:25 UTC
Labels: flaky-test
