### ISSUE TITLE
Able to add duplicate rows with same primary key in dimension table

### ISSUE THREAD

**Issue by madhusudhannsn** [apache/pinot#12284] opened 2024-01-18 17:13 UTC
Hi, I see my dimension table with the following configuration is allowing duplicate rows with same primary key. 
Is this designed by choice or a bug?

**Schema:**
```json
{
    "schemaName": "dim_table_v1",
    "dimensionFieldSpecs": [
      {
        "name": "userId",
        "dataType": "STRING"
      },
      {
        "name": "address",
        "dataType": "STRING",
        "singleValueField": false
      },
      {
        "name": "user_description",
        "dataType": "STRING"
      }
    ],
    "dateTimeFieldSpecs": [
        {
            "name": "last_modified",
            "dataType": "STRING",
            "format": "1:MILLISECONDS:EPOCH",
            "granularity": "1:MILLISECONDS"
        }
    ],
    "primaryKeyColumns": ["userId"]
  }
```
  
  **TableConfig:**
 ```json
 {
    "tableName": "dim_table_v1",
    "tableType": "OFFLINE",
    "segmentsConfig": {
        "schemaName": "dim_table_v1",
        "segmentPushType": "REFRESH",
        "retentionTimeUnit": "DAYS",
        "retentionTimeValue": "90",
        "timeType": "DAYS",
        "replication": "1",
        "minimizeDataMovement": false,
        "segmentAssignmentStrategy": "BalanceNumSegmentAssignmentStrategy",
        "peerSegmentDownloadScheme": "http"
    },
    "tenants": {},
    "tableIndexConfig": {
        "invertedIndexColumns": [
            "userId"
        ],
        "rangeIndexVersion": 1,
        "loadMode": "MMAP",
        "enableDefaultStarTree": false,
        "aggregateMetrics": false,
        "nullHandlingEnabled": false,
        "createInvertedIndexDuringSegmentGeneration": false,
        "autoGeneratedInvertedIndex": false,
        "enableDynamicStarTreeCreation": false,
        "optimizeDictionaryForMetrics": false,
        "noDictionarySizeRatioThreshold": 0.0
    },
    "metadata": {},
    "isDimTable": true
}
```

**Comment by walterddr** [comment] 2024-01-18 22:20
this seems like a bug to me b/c we should not allow 2 rows with the same primary key to be exist in the dimension table. 
however the current behavior is that the newer row is going to override the old row which might be desirable for dimension tables with updates (replacing old entry)

I would imagine both are valid concerns. let me try to see how we can reproduce it

**Comment by madhusudhannsn** [comment] 2024-01-19 04:57
@walterddr ,
"however the current behavior is that the newer row is going to override the old row which might be desirable for dimension tables with updates (replacing old entry)"
I don't see the override behaviour too. When I query the dimension table with the duplicate primary key, I can see all the duplicate records. But when I try lookup joins with a fact table then join is working with only one of the multiple duplicate rows. The behaviour is very inconsistent.

**Comment by walterddr** [comment] 2024-01-19 17:12
hmm. I am not able to reproduce whatever you mentioned here regarding the duplicate primary key behavior. can you share a dataset?

**Comment by walterddr** [comment] 2024-01-22 23:53
feature has been merged. closing this

**Closed by walterddr** 2024-01-22 23:53 UTC
Labels: bug
