### ISSUE TITLE
Improvement: Show "table not found" info in wrong query

### ISSUE THREAD

**Issue by dongxiaoman** [apache/pinot#6328] opened 2020-12-07 19:13 UTC
When we compose/run an adhoc query, we sometimes misspell table names.
The results from query is "Broker resource missing" instead of "table not found", which is quite misleading. It is misleading because sometimes we do run into broker down situation and has the same error.

It will be a small change but with much quality of life improvement. Think about the new users that are trying Pinot and getting such errors could turn them away.

**Comment by kishoreg** [comment] 2020-12-07 19:18
Makes sense, do you want to take it up?

**Comment by dongxiaoman** [comment] 2020-12-07 19:20
Sure, I can help with that. It would be a start to contribute

**Comment by fx19880617** [comment] 2020-12-08 21:43
Thanks @dongxiaoman !

**Comment by shivam621311** [comment] 2020-12-13 05:46
I would like to work on this

**Comment by vijaya-lakshmi-venkatraman** [comment] 2022-02-02 05:12
HI,
I see that there is a merged PR associated with this issue.
Is this still open?

**Comment by Jackie-Jiang** [comment] 2022-02-02 19:06
@vijaya-lakshmi-venkatraman Thanks for the reminder, the issue is resolved

**Closed by Jackie-Jiang** 2022-02-02 19:06 UTC
Labels: enhancement, beginner-task
