### ISSUE TITLE
[flaky test] org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#11962] opened 2023-11-07 21:06 UTC
https://github.com/apache/pinot/actions/runs/6789919525/job/18458169154?pr=11961

```
2023-11-07T20:38:00.6136213Z [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 131.2 s <<< FAILURE! -- in org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest
2023-11-07T20:38:00.6141121Z [ERROR] org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest.testPartitionLevelConsumer -- Time elapsed: 0.748 s <<< FAILURE!
2023-11-07T20:38:00.6143362Z java.lang.AssertionError: expected [500] but found [610]
2023-11-07T20:38:00.6144569Z 	at org.testng.Assert.fail(Assert.java:111)
2023-11-07T20:38:00.6145672Z 	at org.testng.Assert.failNotEquals(Assert.java:1578)
2023-11-07T20:38:00.6146940Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
2023-11-07T20:38:00.6148165Z 	at org.testng.Assert.assertEquals(Assert.java:132)
2023-11-07T20:38:00.6149313Z 	at org.testng.Assert.assertEquals(Assert.java:1419)
2023-11-07T20:38:00.6150602Z 	at org.testng.Assert.assertEquals(Assert.java:1383)
2023-11-07T20:38:00.6151815Z 	at org.testng.Assert.assertEquals(Assert.java:1429)
2023-11-07T20:38:00.6153640Z 	at org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest.testPartitionLevelConsumer(PulsarConsumerTest.java:299)
2023-11-07T20:38:00.6156334Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2023-11-07T20:38:00.6157801Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2023-11-07T20:38:00.6159241Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
2023-11-07T20:38:00.6160796Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
2023-11-07T20:38:00.6162159Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
2023-11-07T20:38:00.6163544Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2023-11-07T20:38:00.6164990Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
2023-11-07T20:38:00.6166460Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
2023-11-07T20:38:00.6167937Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
2023-11-07T20:38:00.6169325Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2023-11-07T20:38:00.6170394Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
2023-11-07T20:38:00.6171282Z 	at org.testng.TestRunner.privateRun(TestRunner.java:848)
2023-11-07T20:38:00.6172063Z 	at org.testng.TestRunner.run(TestRunner.java:621)
2023-11-07T20:38:00.6172853Z 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
2023-11-07T20:38:00.6173740Z 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
2023-11-07T20:38:00.6174676Z 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
2023-11-07T20:38:00.6175548Z 	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
2023-11-07T20:38:00.6176434Z 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
2023-11-07T20:38:00.6177396Z 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
2023-11-07T20:38:00.6178228Z 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
2023-11-07T20:38:00.6179036Z 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
2023-11-07T20:38:00.6179799Z 	at org.testng.TestNG.runSuites(TestNG.java:1114)
2023-11-07T20:38:00.6180428Z 	at org.testng.TestNG.run(TestNG.java:1082)
2023-11-07T20:38:00.6181323Z 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
2023-11-07T20:38:00.6183932Z 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:102)
2023-11-07T20:38:00.6185847Z 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:91)
2023-11-07T20:38:00.6187269Z 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
2023-11-07T20:38:00.6188830Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2023-11-07T20:38:00.6190189Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2023-11-07T20:38:00.6191546Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
2023-11-07T20:38:00.6192799Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
2023-11-07T20:38:00.6193592Z 
2023-11-07T20:38:00.6195380Z [ERROR] org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest.testPartitionLevelConsumerBatchMessages -- Time elapsed: 0.906 s
2023-11-07T20:38:08.4429015Z [ERROR] Failures: 
2023-11-07T20:38:08.4447059Z [ERROR]   PulsarConsumerTest.testPartitionLevelConsumer:299 expected [500] but found [610]
2023-11-07T20:38:08.4448834Z [INFO] 
2023-11-07T20:38:08.4449764Z [ERROR] Tests run: 11, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by Jackie-Jiang** [comment] 2023-11-08 07:48
Duplicate of #8537

**Comment by Jackie-Jiang** [comment] 2023-11-08 07:48
@KKcorps

**Comment by KKcorps** [comment] 2023-11-08 07:50
Yeah, I have tried to reproduce this error in local but I never get it. Will check what can be the root cause

**Comment by xiangfu0** [comment] 2023-11-08 22:39
yeah, maybe need to run it many times

**Comment by Jackie-Jiang** [comment] 2023-11-14 18:26
Duplicate of #8537

**Closed by Jackie-Jiang** 2023-11-14 18:26 UTC
Labels: flaky-test
