### ISSUE TITLE
flaky StarTreeClusterIntegrationTest

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#11910] opened 2023-10-30 22:49 UTC
https://github.com/apache/pinot/actions/runs/6698592598/job/18201002023

**Comment by xiangfu0** [comment] 2023-10-30 23:13
https://github.com/apache/pinot/pull/11911

**Comment by Jackie-Jiang** [comment] 2023-10-30 23:23
```
Error:  Failures: 
Error:    StarTreeClusterIntegrationTest.testGeneratedQueries:164->testStarQuery:185 Query comparison failed for: 
Star Query: SELECT min(DepartureDelayGroups), avg(LateAircraftDelay), distinctCountBitmap(DepartureDelayGroups), avg(LateAircraftDelay), distinctCountBitmap(DepDelay) FROM mytable WHERE Carrier BETWEEN 'UA' AND 'US' AND OriginCityName <> 'Midland/Odessa, TX' AND TotalAddGTime BETWEEN 47 AND 50 AND TotalAddGTime <> 12 AND TotalAddGTime <> 49 AND TotalAddGTime < 97 AND Carrier BETWEEN 'HA' AND 'UA'
Star Response: {"resultTable":{"dataSchema":{"columnNames":["EXPR$0","EXPR$1","EXPR$2","EXPR$3","EXPR$4"],"columnDataTypes":["INT","DOUBLE","LONG","DOUBLE","LONG"]},"rows":[[-9999,-8307.081574675325,16,-8307.081574675325,189]]},"requestId":"1932100833000000194","stageStats":{"1":{"numBlocks":1,"numRows":1,"stageExecutionTimeMs":11,"stageExecutionUnit":1,"stageExecWallTimeMs":12},"2":{"numBlocks":6,"numRows":4,"stageExecutionTimeMs":18,"stageExecutionUnit":4,"stageExecWallTimeMs":7,"tableNames":["mytable"]}},"exceptions":[],"numServersQueried":0,"numServersResponded":0,"numSegmentsQueried":12,"numSegmentsProcessed":12,"numSegmentsMatched":6,"numConsumingSegmentsQueried":0,"numConsumingSegmentsProcessed":0,"numConsumingSegmentsMatched":0,"numDocsScanned":200,"numEntriesScannedInFilter":20842,"numEntriesScannedPostFilter":1000,"numGroupsLimitReached":false,"totalDocs":115545,"timeUsedMs":19,"offlineThreadCpuTimeNs":0,"realtimeThreadCpuTimeNs":0,"offlineSystemActivitiesCpuTimeNs":0,"realtimeSystemActivitiesCpuTimeNs":0,"offlineResponseSerializationCpuTimeNs":0,"realtimeResponseSerializationCpuTimeNs":0,"offlineTotalCpuTimeNs":0,"realtimeTotalCpuTimeNs":0,"segmentStatistics":[],"traceInfo":{},"minConsumingFreshnessTimeMs":0,"numRowsResultSet":1,"numSegmentsPrunedByBroker":0,"numSegmentsPrunedByServer":0,"numSegmentsPrunedInvalid":0,"numSegmentsPrunedByLimit":0,"numSegmentsPrunedByValue":0,"explainPlanNumEmptyFilterSegments":0,"explainPlanNumMatchAllFilterSegments":0,"brokerId":"Broker_10.1.0.108_28089","brokerReduceTimeMs":1}
Reference Query: SET useStarTree = false; SELECT min(DepartureDelayGroups), avg(LateAircraftDelay), distinctCountBitmap(DepartureDelayGroups), avg(LateAircraftDelay), distinctCountBitmap(DepDelay) FROM mytable WHERE Carrier BETWEEN 'UA' AND 'US' AND OriginCityName <> 'Midland/Odessa, TX' AND TotalAddGTime BETWEEN 47 AND 50 AND TotalAddGTime <> 12 AND TotalAddGTime <> 49 AND TotalAddGTime < 97 AND Carrier BETWEEN 'HA' AND 'UA'
Reference Response: {"resultTable":{"dataSchema":{"columnNames":["EXPR$0","EXPR$1","EXPR$2","EXPR$3","EXPR$4"],"columnDataTypes":["INT","DOUBLE","LONG","DOUBLE","LONG"]},"rows":[[-1,-1999.6,5,-1999.6,5]]},"requestId":"1932100833000000195","stageStats":{"1":{"numBlocks":1,"numRows":1,"stageExecutionTimeMs":7,"stageExecutionUnit":1,"stageExecWallTimeMs":7},"2":{"numBlocks":6,"numRows":4,"stageExecutionTimeMs":6,"stageExecutionUnit":4,"stageExecWallTimeMs":7,"tableNames":["mytable"]}},"exceptions":[],"numServersQueried":0,"numServersResponded":0,"numSegmentsQueried":12,"numSegmentsProcessed":12,"numSegmentsMatched":3,"numConsumingSegmentsQueried":0,"numConsumingSegmentsProcessed":0,"numConsumingSegmentsMatched":0,"numDocsScanned":5,"numEntriesScannedInFilter":124456,"numEntriesScannedPostFilter":15,"numGroupsLimitReached":false,"totalDocs":115545,"timeUsedMs":18,"offlineThreadCpuTimeNs":0,"realtimeThreadCpuTimeNs":0,"offlineSystemActivitiesCpuTimeNs":0,"realtimeSystemActivitiesCpuTimeNs":0,"offlineResponseSerializationCpuTimeNs":0,"realtimeResponseSerializationCpuTimeNs":0,"offlineTotalCpuTimeNs":0,"realtimeTotalCpuTimeNs":0,"segmentStatistics":[],"traceInfo":{},"minConsumingFreshnessTimeMs":0,"numRowsResultSet":1,"numSegmentsPrunedByBroker":0,"numSegmentsPrunedByServer":0,"numSegmentsPrunedInvalid":0,"numSegmentsPrunedByLimit":0,"numSegmentsPrunedByValue":0,"explainPlanNumEmptyFilterSegments":0,"explainPlanNumMatchAllFilterSegments":0,"brokerId":"Broker_10.1.0.108_28089","brokerReduceTimeMs":0}
Random Seed: 1698701502299: Iterators differ at element [1]: [[-1,-1999.6,5,-1999.6,5]] != [[-9999,-8307.081574675325,16,-8307.081574675325,189]] expected [[[-1,-1999.6,5,-1999.6,5]]] but found [[[-9999,-8307.081574675325,16,-8307.081574675325,189]]]
```

**Comment by Jackie-Jiang** [comment] 2023-10-30 23:24
Duplicate of #11718

**Comment by Jackie-Jiang** [comment] 2023-11-01 17:38
I don't follow why this test failure is related to ZK port

**Closed** 2023-11-14 18:27 UTC
Labels: flaky-test
