### ISSUE TITLE
[multistage] [stability] Clean up MailboxService Concurrent Map 

### ISSUE THREAD

**Issue by 61yao** [apache/pinot#9625] opened 2022-10-18 21:36 UTC
Currently, the msg instance got queued in mailbox service concurrent map and never gets cleaned up.

Tracked the issue here.

@walterddr

**Comment by walterddr** [comment] 2022-10-18 22:11
duplicate of https://github.com/apache/pinot/issues/9625. added more context there

**Closed by walterddr** 2022-10-18 22:11 UTC
