### ISSUE TITLE
Segments go into error state after adding sortedColumn on already existing realtime table

### ISSUE THREAD

**Issue by priyen** [apache/pinot#8962] opened 2022-06-23 14:34 UTC
At Stripe we recently tried adding a sortedColumn on a realtime table that already exists and noticed that we see these logs, and then the segment goes into error start until we restart the server.

```[2022-06-20 20:18:54.399523] 2022/06/20 20:18:54.399 INFO [LLRealtimeSegmentDataManager_<SEGMENT NAME>] [HelixTaskExecutor-message_handle_thread] RealtimeDataResourceZKMetadata **contains no information about sorted column for segment** <SEGMENT NAME>```

Adding sortedColumn to an existing realtime table isn't a safe change, this seems like a bug.

**Comment by Jackie-Jiang** [comment] 2022-06-23 22:06
In order to sort records within a consuming segment, inverted index is required. Currently there is no easy way to add an inverted index into a consuming segment, so there are 2 options:
1. Re-design segment reload for consuming segment. Currently segment reload can only add new column with default value, which is not robust and can cause unexpected behavior when there are other changes in the table config. In order to apply the complete table config into the current consuming segment without waiting for it to commit, we need to re-consume the segment. To avoid inconsistent query result, we can consider pausing the current consuming segment and start a new one, wait for it to catch up and then replace the old one.
2. Make sorting possible without inverted index.

IMO option 1 is more desired because option 2 can cause extra overhead when committing the segment, and won't fix the other issues caused by reloading a consuming segment.

**Comment by mcvsubbu** [comment] 2022-06-23 22:20
@priyen did the column exist when you changed the table config to set the column name to be sorted? (Btw, we can only sort on one column, even though it is an array in the table config. Adding second and subsequent col names to the array does not have any effect, iirc).

Maybe this is as simple as not throwing the error if information is not available while constructing the segment. the next segment will pick up the sorting info correctly (and create the inverted index while consuming)

**Comment by Jackie-Jiang** [comment] 2023-07-21 08:07
With #9640 consuming segment will no longer add temporary columns during reload, so this problem should be solved

**Closed by Jackie-Jiang** 2023-07-21 08:07 UTC
Labels: bug
