### ISSUE TITLE
Flaky Test for `ForwardIndexHandlerTest`

### ISSUE THREAD

**Issue by snleee** [apache/pinot#10012] opened 2022-12-20 21:33 UTC
```
Error:  Failures: 
Error:  org.apache.pinot.segment.local.segment.index.loader.ForwardIndexHandlerTest.setUp
Error:    Run 1: ForwardIndexHandlerTest.setUp:194->buildSegment:205->createTestData:389 » IllegalArgument
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
[INFO]   Run 5: PASS
[INFO]   Run 6: PASS
[INFO]   Run 7: PASS
[INFO]   Run 8: PASS
[INFO]   Run 9: PASS
[INFO]   Run 10: PASS
[INFO]   Run 11: PASS
[INFO] 
[INFO] 
Error:  Tests run: 3118, Failures: 1, Errors: 0, Skipped: 11
```

```
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    ForwardIndexHandlerTest.testDisableForwardIndexForMultipleRawColumns:1334->validateMetadataProperties:1869 METRIC_SNAPPY_BIG_DECIMAL expected [11] but found [10]
Error:    ForwardIndexHandlerTest.testDisableForwardIndexForSingleRawColumn:1379->validateMetadataProperties:1869 METRIC_SNAPPY_BIG_DECIMAL expected [11] but found [10]
Error:    ForwardIndexHandlerTest.testEnableDictionaryForMultipleColumns:1047->validateMetadataProperties:1869 METRIC_SNAPPY_BIG_DECIMAL expected [11] but found [10]
Error:    ForwardIndexHandlerTest.testEnableDictionaryForSingleColumn:1090->validateMetadataProperties:1869 METRIC_SNAPPY_BIG_DECIMAL expected [11] but found [10]
[INFO] 
Error:  Tests run: 3117, Failures: 4, Errors: 0, Skipped: 0
```
I was not able to reproduce this locally.

**Comment by snleee** [comment] 2022-12-20 21:34
@vvivekiyer @somandal Can you double check the test logic if there's any obvious issue for flaky test? Or, the test may be expensive run on the github action.

**Comment by Jackie-Jiang** [comment] 2022-12-21 23:54
The first one should be fixed in #10018

**Comment by richardstartin** [comment] 2022-12-31 19:54
I encountered this on master just now, I saw it in CI for #10044 and thought it was caused by my changes, so dug into it a bit. I had to run about 10 times locally before it flaked in master.

```
java.lang.AssertionError: METRIC_SNAPPY_BIG_DECIMAL
Expected :11
Actual   :10
<Click to see difference>


	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.apache.pinot.segment.local.segment.index.loader.ForwardIndexHandlerTest.validateMetadataProperties(ForwardIndexHandlerTest.java:1869)
	at org.apache.pinot.segment.local.segment.index.loader.ForwardIndexHandlerTest.testEnableDictionaryForSingleColumn(ForwardIndexHandlerTest.java:1090)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

**Comment by walterddr** [comment] 2023-01-04 18:41
duplicate of https://github.com/apache/pinot/issues/9831 ?

**Closed** 2023-02-17 23:51 UTC
Labels: flaky-test
