### ISSUE TITLE
Support replacing real-time committed segment

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/pinot#6362] opened 2020-12-17 00:40 UTC
Real-time committed segment is very similar to offline segment with the following differences:
- It has metadata of consuming start/end offset
- Its name follows the real-time segment naming convention (stream info and time info embedded)

For LLC committed segment, it should be possible to replace the existing segment with a new segment covering the same consuming start/end offset.
This feature will be useful in the following scenarios:
- Data correction
- Segment purge
- Segment re-indexing

**Comment by mcvsubbu** [comment] 2020-12-17 01:18
Remember to add in metadata some information about which data center this was produced in. This will make sure that we cannot (even accidentally) replace segments across data centers.

**Comment by Jackie-Jiang** [comment] 2020-12-17 01:38
@mcvsubbu Can you please elaborate more about this? Are we planning to add this check for offline segment pushes as well? Real-time committed segment refresh should follow the same code path with the offline segment refresh.

**Comment by mcvsubbu** [comment] 2020-12-17 02:13
I thought the issue was to cover the case of replacing committed segments  in realtime. Is that right? If so, offsets of the topic in one data center will not match that of another one, and it is not possible to replace segments from one to another

**Comment by Jackie-Jiang** [comment] 2020-12-17 18:55
@mcvsubbu This is mainly for minion to purge/update the segment, which will include the crc check to ensure the segment is the same before replacing. I feel crc check should be enough, and is more general to prevent pushing the wrong segment

**Comment by yupeng9** [comment] 2020-12-17 19:27
What's the relationship between this issue and [segment merge/rollup](https://github.com/apache/incubator-pinot/issues/2715)? Also, is there common work with the [tiered storage solution](https://docs.google.com/document/d/1Z4FLg3ezHpqvc6zhy0jR6Wi2OL8wLO_lRC6aLkskFgs/edit#heading=h.io8oektr60xq)?

**Comment by Jackie-Jiang** [comment] 2020-12-17 21:37
@yupeng9 In the current design, merge/rollup can only be applied to offline table, but conceptually it should also work on realtime table. In order to make it work for real-time table, we need to support pushing (instead of replacing) new segments for real-time table. That is the next stage of this issue, and more complicated because we need to figure out how to handle the start/offset information. We might start another issue when trying to support adding new real-time segments.
This issue is not very related to the tiered storage.

**Comment by mcvsubbu** [comment] 2020-12-17 23:31
> @mcvsubbu Can you please elaborate more about this? Are we planning to add this check for offline segment pushes as well? Real-time committed segment refresh should follow the same code path with the offline segment refresh.

Right now, realtime segments are not accepted when we try to upload them via rest api. I am guessing this has to do with opening up that rest api as well. If so, then we should make sure that we only accept the segments that were built in the same data center (for which we need to add some metadata to the realtime segment while building it).

**Comment by yupeng9** [comment] 2020-12-18 06:07
> @yupeng9 In the current design, merge/rollup can only be applied to offline table, but conceptually it should also work on realtime table. In order to make it work for real-time table, we need to support pushing (instead of replacing) new segments for real-time table. That is the next stage of this issue, and more complicated because we need to figure out how to handle the start/offset information. We might start another issue when trying to support adding new real-time segments.
> This issue is not very related to the tiered storage.

I see. Yes, I think this will be a big enabler to several features. About tiered storage, since it has the logic of moving segments across medium, I thought it can use the same replace API that you want to introduce in this issue.

**Comment by Jackie-Jiang** [comment] 2020-12-18 18:57
@yupeng9 I'll use the same API as the offline segment push, and support refreshing real-time committed segment

**Comment by laxmanchekka** [comment] 2021-02-17 03:32
@Jackie-Jiang : is this duplicate of https://github.com/apache/incubator-pinot/pull/6567

**Comment by Jackie-Jiang** [comment] 2021-02-17 20:36
@laxmanchekka #6567 can solve this issue, and has a bigger scope as it also supports uploading new segment instead of replacing existing segment.

**Closed** 2022-10-12 20:40 UTC
Labels: feature
