### ISSUE TITLE
Using Kinesis, server stops consuming data

### ISSUE THREAD

**Issue by FranMorilloAWS** [apache/pinot#11271] opened 2023-08-04 16:35 UTC
Even tough in Pinot UI, it shows table to be healthy, it stops consuming messages from the Kinesis Data Stream. 

By going into the Server logs I can see that it is trying to commit the segments but to localhost:9000, however my cluster is decoupled in multiple ec2 instances. 

Is there any additional configuration I need to give to the Table or Server, so it doesnt think that the controller is running in the same host?

**Comment by Jackie-Jiang** [comment] 2023-08-08 19:27
This is not really related to Kinesis, but the controller address. Can you check if you also have a controller deployed on the same node? Per the symptom you described, the controller address is not correct. You may look up the controller address in the controller panel within the cluster manager

**Comment by Jackie-Jiang** [comment] 2023-08-08 19:29
Duplicate of #9869. Closing this one and move the discussion there

**Closed by Jackie-Jiang** 2023-08-08 19:29 UTC
