### ISSUE TITLE
The race condition that TableDataManager is removed during segment download because of incorrect segment count.

### ISSUE THREAD

**Issue by jtao15** [apache/pinot#8423] opened 2022-03-28 07:26 UTC
Current code does the followings:

1. `tableDataManager` uses `segmentDataManagerMap` to track the segments. `tableDataManager` is created and initialized when adding the first segment to the server, and shutdown if the last segment is removed.
2. The `tmp` directory for temporarily storing new downloaded segments will be removed and recreated as part of `tableDataManager` initialization.
3. When adding a new segment to server, the server will download the segment first and update the segmentDataManagerMap after.

This can cause two issues:
1. If the last segment is removed from `segmentDataManagerMap` during new segment download time and before updating `segmentDataManagerMap`, the `tableDataManager` will be shutdown, and the new segment will become unreachable. We will have partial query results with `SERVER_SEGMENT_MISSING_ERROR`.
2. If `tableDataManager` is initialized during the segment download in scenario 1, the downloaded tar file will be removed. The server will take it as download failure, and the segment will stay in `ERROR` state until fixed manually by restarting the server. We have observed this issue recently after #7961 was merged.

**Comment by Jackie-Jiang** [comment] 2022-03-29 20:15
After some offline discussion, one way to solve this issue is to add a `DELETE` message, and only remove the `tableDataManager` when the table is deleted

**Comment by jadami10** [comment] 2022-03-30 19:50
Just to confirm my understanding, #7961 surfaced this bug because it's deleting tmp files or it's causing it?

**Comment by Jackie-Jiang** [comment] 2022-03-31 23:08
@jadami10 @mcvsubbu The root cause is the effect of combining #6608 and #7961
When #6608 is introduced, there is no side effect of closing and recreating the table data manager (kind of stateless). But with the deleting tmp dir logic introduced in #7961, the table data manager is stateful even if it is empty.

**Comment by npawar** [comment] 2022-05-03 22:19
has this been resolved? can the issue be closed?

**Closed** 2023-10-13 20:30 UTC
