### ISSUE TITLE
[pinot] Throw error when column doesn't exist during aggregations

### ISSUE THREAD

**Issue by Aka-shi** [apache/pinot#6303] opened 2020-12-01 04:33 UTC
As of now, when we call an aggregate function on a column which doesn't exist in the pinot table, the query returns the default value for that aggregation type instead of throwing `column doesn't exist` or `column cannot be found in <table>` kind of error. This would be misleading for the user as the query will succeed. 

Example Query:
`select max(blah) from transcripts` - this returns `-infinity`.

**Comment by kishoreg** [comment] 2020-12-01 04:51
@jackjlli there was some implementation on this right?

**Comment by jackjlli** [comment] 2020-12-01 20:08
Correct, we have a PR for that: https://github.com/apache/incubator-pinot/pull/6066

**Comment by gortiz** [comment] 2022-08-08 10:42
IICU #6066 was closed because the feature was actually added in #7590. But I can confirm that it is still present in Pinot 0.11.0-SNAPSHOT

**Comment by Jackie-Jiang** [comment] 2022-08-08 17:44
Yes, the issue is fixed in #7590 which is released in 0.9.0. Closing the ticket

**Closed by Jackie-Jiang** 2022-08-08 17:44 UTC
Labels: bug, help wanted
