### ISSUE TITLE
 DATETIMECONVERT udf does not work for customized timezone and bucket size > 1 day

### ISSUE THREAD

**Issue by chenboat** [apache/pinot#3513] opened 2018-11-19 18:23 UTC
When running the following query using the DATETIMECONVERT udf, we encounter the following query execution exception (we notice the exception disappear when we change the bucket size from 7 to 1 day):
`QueryExecutionError:\norg.joda.time.IllegalFieldValueException: Value 0 for dayOfMonth must be in the range [1,30]\n\tat org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:234)\n\tat org.joda.time.field.PreciseDurationDateTimeField.set(PreciseDurationDateTimeField.java:79)\n\tat org.joda.time.chrono.ZonedChronology$ZonedDateTimeField.set(ZonedChronology.java:496)\n\tat org.joda.time.DateTime.withDayOfMonth(DateTime.java:1782)\n\tat com.linkedin.pinot.core.operator.transform.transformer.datetime.BaseDateTimeTransformer.lambda$new$4(BaseDateTimeTransformer.java:95)\n\tat com.linkedin.pinot.core.operator.transform.transformer.datetime.BaseDateTimeTransformer.transformMillisToSDF(BaseDateTimeTransformer.java:119)\n\tat com.linkedin.pinot.core.operator.transform.transformer.datetime.EpochToSDFTransformer.transform(EpochToSDFTransformer.java:37)\n\tat com.linkedin.pinot.core.operator.transform.function.DateTimeConversionTransformFunction.transformToStringValuesSV(DateTimeConversionTransformFunction.java:154)\n\tat com.linkedin.pinot.core.operator.docvalsets.TransformBlockValSet.getStringValuesSV(TransformBlockValSet.java:68)\n\tat com.linkedin.pinot.core.query.aggregation.groupby.NoDictionarySingleColumnGroupKeyGenerator.generateKeysForBlock(NoDictionarySingleColumnGroupKeyGenerator.java:95)\n\tat com.linkedin.pinot.core.query.aggregation.groupby.DefaultGroupByExecutor.process(DefaultGroupByExecutor.java:135)\n\tat com.linkedin.pinot.core.operator.query.AggregationGroupByOperator.getNextBlock(AggregationGroupByOperator.java:78)\n\tat com.linkedin.pinot.core.operator.query.AggregationGroupByOperator.getNextBlock(AggregationGroupByOperator.java:35)\n\tat com.linkedin.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:42)"`

**Query**:
select count(source_start_utc_time) from some_table where ... GROUP BY DATETIMECONVERT(source_start_utc_time, '1:SECONDS:EPOCH', '1:DAYS:SIMPLE_DATE_FORMAT:yyyyMMdd tz(America/Chicago)', '7:DAYS')

**Data to reproduce the issue**
"columns": ["source_start_utc_time"],
        "results": [
            ["1541534400"],
            ["1541579400"],
            ["1541539800"],
            ["1541566500"],
            ["1541559600"],
            ["1541563200"],
            ["1541608200"],
            ["1541545200"],
            ["1541611800"],
            ["1541541600"]
        ]

**Comment by npawar** [comment] 2018-11-20 01:04
I was able to reproduce this issue. The root cause for this, is this switch case for DAYS in [BaseDateTimeTransformer](https://github.com/apache/incubator-pinot/blob/master/pinot-core/src/main/java/com/linkedin/pinot/core/operator/transform/transformer/datetime/BaseDateTimeTransformer.java). This is where the _dateTimeTruncate is created, which is needed for  converting millis to sdf. This only happens in cases where final output is expected in SDF

```
case DAYS:
        _dateTimeTruncate = (dateTime) -> _outputDateTimeFormatter.print(
          dateTime.withDayOfMonth(
            (dateTime.getDayOfMonth()/sz)*sz
          ).dayOfMonth().roundFloorCopy()
        );
        break;
```

The problem is `dateTime.getDayOfMonth()` will return values in [1-31]. `sz` is the output granularity. If the granularity happens to be greater than the dayOfMonth, division will give us `0`.
For example, in your case, outputGranularity=7 DAYS, and hence sz=7. So for days 1-6 this will fail.
Which is also why it works when you try `1:DAYS` because there is no `0` generated in the division.

The fix for this would depend on what the right output for this should be. The current logic will always create output based on the local boundary (for cases where output is in SDF)
For example:
Below is a list of UTC millis, starting 2018-09-19T00:00:00 to 2018-10-09T00:00:00. The second column is the output of applying 
`dateTimeConvert(millis, '1:MILLISECONDS:EPOCH', '1:DAYS:EPOCH', '7:DAYS')`
The third column is the output of applying
`dateTimeConvert(millis, '1:MILLISECONDS:EPOCH', '1:DAYS:SIMPLE_DATE_FORMAT:yyyyMMdd', '7:DAYS')`
**They are not equivalent.**
```
1537315200000L, 20180914, 17787
1537401600000L, 20180914, 17794
1537488000000L, 20180921, 17794
1537574400000L, 20180921, 17794
1537660800000L, 20180921, 17794
1537747200000L, 20180921, 17794
1537833600000L, 20180921, 17794
1537920000000L, 20180921, 17794
1538006400000L, 20180921, 17801
1538092800000L, 20180928, 17801
1538179200000L, 20180928, 17801
1538265600000L, 20180928, 17801
```
In the first case, bucketing is done starting from **epoch start**.
In the second case, bucketing is done such that the **start of the month resets the start of the bucketing** (this is because of the use of dayOfMonth to set the day) .
Not stating that this approach is right or wrong, just explaining how it is working at the moment.
This is how it would work for other granularities as well (hours bucketing will reset at the day boundary, etc)

The fixes for this could be:
1) Preserve this behavior. In that case for days 1-7 of the month (2018-09-01 to 2018-09-07), we would get 1 bucket (2018-09-01), for days 8-14 we would get bucket 2 (2018-09-08). 
This would be the easiest fix, we would only need to make some changes to the division in that code block pasted above.
2) Make the bucketing for SDF also work starting epoch. This would need some refactoring of how this bucketing is done for SDF cases. Not sure if anyone is using this UDF and depending on the particular behavior. (@subprotocol )
3) Leave this as is for now. For your specific usecase, you can use `(millis, '1:MILLISECONDS:EPOCH', '1:DAYS:EPOCH', '7:DAYS')` and convert the millis later to what you need.

@kishoreg

**Comment by chenboat** [comment] 2018-11-20 06:48
@npawar Thanks for the investigation. It really helps. In our use cases, the client first wanted to use "1 week" as the bucket size or granularity. When they found out it did not work because 'week' is not supported, they switched to use 7 days (probably without understanding the semantics). So the ideal fix is to make **week** work as a legit bucket unit because alignment by calendar weeks is more intuitive to users. Is it possible to do it? Otherwise, we can spell out the plausible combinations of parameters in this UDF[doc](https://github.com/apache/incubator-pinot/wiki/dateTimeConvert-UDF) -- I guess the users find 1:WEEKS there.  

As for fixing the issue with the granularity in terms of  **days**, I would say both (1) and (2) are fine as long as we define it clearly in the same UDF doc. As far as I know, there is no well known notion about how to align a general N days bucket: so most of users can accept a definition and decide if it works for them. (3) is not working for us in this case because our users do want to the Pinot feature to convert the time to a local timezone (e.g, Chicago).

**Comment by npawar** [comment] 2018-11-20 19:35
If we were to support WEEKS in output granularity, where should the bucketing align from? In case of outputFormat in EPOCH, the bucketing can just be done in epoch weeks. But if output is in SDF, we have many options

- If we start bucketing from epoch start, January 1st 1970 was a Thursday, so all buckets would be starting Thursday. 
- If we want a calendar alignment, should we start Monday/Sunday?
- If we keep current behavior, days 1-7 would align with bucket yyyyMM01, days 8-14 with yyyyMM08 and so on. The number of week buckets in a year will not equal to 52 in this case, as we will have a half bucket created for every month's last few days.

I prefer option 1, seems the most predictable and clean approach. We can also make all bucketing follow this. No resetting buckets at boundaries (DAYS should not reset at month, HOURS should not reset on days). But this would mean, you will not get a calendar alignment, and would have to offset your date if you need it aligned to the calendar.

@kishoreg @mayankshriv please provide your suggestions if possible.

**Comment by weiwanning** [comment] 2019-03-20 23:28
hey @npawar, went into the same issue, option2 seems ideal for my use case(better to make Mon/Sun/... as an option), also could we support MONTHS and YEARS together with WEEKS?

**Comment by npawar** [comment] 2019-03-29 23:20
Hey @chenboat and @weiwanning,
I won't be able to get to this anytime soon. Would you like to take a stab at making the enhancement? I would be happy to go over the design and all the cases we might encounter.

**Comment by agrawaldevesh** [comment] 2020-09-14 22:58
FWIW, @chenboat  I added a preso compatible date_trunc that handles your ask: https://github.com/apache/incubator-pinot/pull/4740.

**Closed** 2022-08-09 23:24 UTC
