### ISSUE TITLE
PulsarConsumerTest.testPartitionLevelConsumer is flaky

### ISSUE THREAD

**Issue by richardstartin** [apache/pinot#8690] opened 2022-05-12 20:01 UTC
https://github.com/apache/pinot/runs/6412121833?check_suite_focus=true

**Comment by Jackie-Jiang** [comment] 2022-05-13 01:11
@KKcorps Can you please take a look? I also got this failure in #8677, not sure if they are related (not likely related though)

**Comment by xiangfu0** [comment] 2022-05-13 01:53
Another try: https://github.com/apache/pinot/pull/8691

**Comment by KKcorps** [comment] 2022-05-13 06:44
Looking into it. I am still not able to understand why this error occurs at randomly and is impossible to produce in local.

**Comment by Jackie-Jiang** [comment] 2022-05-13 23:54
Usually the test failure that is hard to reproduce locally is due to the slowness of the CI machines. We may use `TestUtils.waitForCondition()` if the condition is not guaranteed to be met at the first place

**Comment by Jackie-Jiang** [comment] 2023-11-14 18:25
Duplicate of #8537

**Closed by Jackie-Jiang** 2023-11-14 18:25 UTC
Labels: flaky-test
