### ISSUE TITLE
Query having just "one aggregation with filter" produces no result if aggregation' filter does not match any record

### ISSUE THREAD

**Issue by kmozaid** [apache/pinot#13982] opened 2024-09-12 06:07 UTC
`select AirlineId, count(*) filter (where OriginStateName = 'xyz') from airlineStats group by AirlineId limit 10` - This query does not produce any result.

`select AirlineId, count(*) filter (where OriginStateName = 'xyz'), count(*) from airlineStats group by AirlineId limit 10` - Here added one more aggregation, now it will produce the result, and "aggregation with filter" column will have value as 0 in all rows.

`select AirlineId, count(*) filter (where OriginStateName = 'xyz') from airlineStats group by AirlineId limit 10` and `select AirlineId, count(*) from airlineStats where OriginStateName = 'xyz' group by AirlineId limit 10` queries are behaving same, although user expect all matching group keys to return with value as 0

**Comment by Jackie-Jiang** [comment] 2024-09-12 18:58
Related to #12647

**Comment by protyay** [comment] 2024-09-21 15:23
Hi @Jackie-Jiang , I want to get this issue assigned to me. Is there a process to get it assigned ?

**Comment by protyay** [comment] 2024-09-28 11:01
Thanks. Started triaging the issue.

**Comment by yashmayya** [comment] 2024-10-18 09:36
@protyay apologies for taking over this issue - looks like it was a duplicate of https://github.com/apache/pinot/issues/12647, and has been fixed in https://github.com/apache/pinot/pull/14211.

**Closed by yashmayya** 2024-10-18 09:36 UTC
Labels: bug
