### ISSUE TITLE
Got empty result from a Multi-valued column when using Lookup join between a fact table and dimension table

### ISSUE THREAD

**Issue by yf-45** [apache/pinot#12272] opened 2024-01-16 16:48 UTC
Hi team,

I tried to use lookup join a fact table with a dimension table, but I got empty result for a Multi-valued column(String type) from the dimension table, is it a bug? any workaround?

e.g.
SELECT
fact_id,
fact_col1,
LOOKUP('dimensiont_table', 'mutli_valued_column', 'fact_id', fact_id) AS col2, -- nothing returned
LOOKUP('dimensiont_table', 'single_value_column', 'fact_id', fact_id) AS col3 -- do have the value returned
FROM fact_table

thanks

**Comment by walterddr** [comment] 2024-01-17 03:04
hello @yf-45 do you have a minimum repro dataset we can use to identify the problem?

**Comment by yf-45** [comment] 2024-01-17 09:54
thanks @walterddr for replying. 
sure, for the dimension table schema is
`
{
  "schemaName": "dimension_table",
  "dimensionFieldSpecs": [
    {
      "name": "fact_id",
      "dataType": "STRING"
    },
    {
      "name": "single_value_column",
      "dataType": "STRING"
    },
    {
      "name": "multi_value_column",
      "dataType": "STRING",
      "singleValueField": false
    }
  ],
  "dateTimeFieldSpecs": [
    {
      "name": "last_updated_date",
      "dataType": "LONG",
      "format": "1:MILLISECONDS:EPOCH",
      "granularity": "1:MILLISECONDS"
    }
  ],
  "primaryKeyColumns": [
    "org_id"
  ]
}
`
for the fact table schema is:
`
{
  "schemaName": "fact_table",
  "dimensionFieldSpecs": [
    {
      "name": "fact_id",
      "dataType": "STRING"
    },
    {
      "name": "fact_col1",
      "dataType": "STRING"
    },   
  ],
  "dateTimeFieldSpecs": [
    {
      "name": "ts",
      "dataType": "LONG",
      "format": "1:MILLISECONDS:EPOCH",
      "granularity": "1:SECONDS"
    }  
  ],
  "primaryKeyColumns": [
    "fact_id"
  ]
}
`
Data for dimension table:
`
[
  {
    "fact_id": "003387f5-ec7a-4231-8b36-42c4c438c725",
    "single_value_column": "some single value data",
    "multi_value_column": ["multi_value_1", "multi_value_2"],
    "last_updated_date": "1690227815000"
  }
  ]
  `
  
 Data for fact table:  
`
[
  {
    "fact_id": "003387f5-ec7a-4231-8b36-42c4c438c725",
     "fact_col1": "some value",
     "ts": "1690227815000"
  }
  ]
  `

**Comment by walterddr** [comment] 2024-01-17 17:13
i couldn't reproduce. there are several things that needs to be fixed in order to get this right

1. your dim table is on `"primaryKeyColumns": ["id", "fact_id"]` i had to make it to just `fact_id` in order to get your query running
2. there's a chance that you saw the default null value for the results that's not joined successfully. 

LOOKUP is essentially a "LEFT JOIN" which will keep every row on the left table and put default null value to the columns that didn't match on the LOOKUP right table. the default value for multi-value-column is empty and the default value for int is INTEGER_MIN and the default value for string is `"null"`.

**Comment by yf-45** [comment] 2024-01-18 12:21
@walterddr , sorry, my bad. I have updated the configurations in the earlier comment.

So here is what I got multivalues is empty
![image](https://github.com/apache/pinot/assets/3345575/ffef4f5e-a058-4dbc-874c-2ebb4eda661a)

but if you select directly from the dimension table, it has values
![image](https://github.com/apache/pinot/assets/3345575/30375f41-d601-414e-8bcc-a2241b526548)

**Comment by walterddr** [comment] 2024-01-18 16:10
still can't reproduce it. can you share your table config for both?

**Comment by walterddr** [comment] 2024-01-19 18:36
confirm this is fixed in latest master.

**Closed by walterddr** 2024-01-19 18:36 UTC
Labels: troubleshooting
