### ISSUE TITLE
Improve Syntax Error Messages

### ISSUE THREAD

**Issue by ege-st** [apache/pinot#10921] opened 2023-06-15 14:20 UTC
Syntax error messages are very hard to read. Usually, they are just stack traces from Calcite along with an HTTP Code 200. This creates a very confusing message for users: a stack trace tells the user that the database itself has faulted but the 200 code says that everything is fine. Compounding the problem is that the stack trace is the same across all syntax error messages; therefore, it does not provide any information on what the syntax problem is or how to fix it.

The result is a poor user experience for a person trying to learn how to use Pinot and for experienced people writing complex queries.

The goal for this ticket is to have Pinot return human readable error messages for syntax problems or provide enough information for the user to easily understand what caused the error.

### Example
This query `select * from mytable WHEE ActualElapsedTime = 100` returns this error:

```
SQLParsingError:
java.lang.Exception: Unable to parse the SQL: 'select * from mytable WHEE ActualElapsedTime = 100'
	at org.apache.pinot.controller.api.resources.PinotQueryResource.executeSqlQuery(PinotQueryResource.java:144)
	at org.apache.pinot.controller.api.resources.PinotQueryResource.handlePostSql(PinotQueryResource.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

It should return something which states that `WHEE` is invalid like `Invalid keyword: 'WHEE'` or `Expected 'WHERE' but found 'WHEE'`.

**Comment by Jackie-Jiang** [comment] 2023-06-17 01:48
Great suggestion!
Currently we simply return the exception thrown by the Calcite SQL parser. We can explore if Calcite supports identifying the syntax error from a query.

**Comment by abhioncbr** [comment] 2023-06-18 01:15
It's possible through Calcite, IMO. I was once looking at the [code](https://github.com/apache/calcite/blob/main/core/src/main/java/org/apache/calcite/sql/advise/SqlAdvisor.java#L603), and it seems like it can help us in achieving the ask.

I want to try it if it's not urgent and no one is working on it. Please assign it to me. Thanks

**Comment by ege-st** [comment] 2023-06-20 13:29
Awesome, thank you.

**Comment by mayankshriv** [comment] 2023-06-21 16:27
@abhioncbr thanks, I have assigned this to you now.

**Comment by abhioncbr** [comment] 2023-06-26 03:25
I tried to use the [Calcite SqlAdvisor code](https://github.com/apache/calcite/blob/main/core/src/main/java/org/apache/calcite/sql/advise/SqlAdvisor.java#L603) mentioned in my above comment for the below incorrect query

```SELECT intCol FROMM select_expression_test_tbl1```
 
and the error message I got for the above query is below
```
Encountered "select_expression_test_tbl1" at line 1, column 21.
Was expecting one of:
    <EOF> 
    "EXCEPT" ...
    "FETCH" ...
    "FROM" ...
    "INTERSECT" ...
    "LIMIT" ...
    "OFFSET" ...
    "ORDER" ...
    "MINUS" ...
    "UNION" ...
    "," ...
```

It is a bit much better than our current exception message content
```
Encountered " <IDENTIFIER> "select_expression_test_tbl1 "" at line 1, column 21.
Was expecting:
    <EOF> 
```

I am not sure if it's more helpful or not. 

@walterddr do you have any ideas around this? Thanks

**Comment by abhioncbr** [comment] 2023-06-29 19:32
Thanks, @walterddr; I noticed one issue because of my [changes](https://github.com/apache/pinot/commit/dc3b6fd3192b9301017e91a564241479e67727b9#diff-2ef8e7d90492c8e2f69f0b08251ec4d0882900f78bbd40c72152b1632657a66cL136). I am going to raise the PR for the fix. Thanks

**Comment by walterddr** [comment] 2023-06-29 21:47
yup ^ that's where. it should encapsulate not just the sqlQuery but also the error

**Comment by abhioncbr** [comment] 2023-07-01 00:27
@ege-st, can we close this issue or any further work you have in mind? Thanks

**Comment by walterddr** [comment] 2023-07-01 00:30
ah. actually i have a follow up @abhioncbr 

in your PR's description. you can see that the query is single-lined --> if the query is multiple line. can you confirm that if the query has more than 5 lines the error is going to be truncated? (e.g. it will show the first 5 line of the error, then the Cause by)

if that happens, i was wondering if we should squash the multi-line query into just 1

**Comment by abhioncbr** [comment] 2023-07-01 00:38
Got it; that's a very going point. I'll confirm it here. Thanks.

**Comment by abhioncbr** [comment] 2023-07-01 01:04
It seems good enough to me.

<img width="1135" alt="Screen Shot 2023-06-30 at 9 03 02 PM" src="https://github.com/apache/pinot/assets/1076944/d432909f-d12b-4c5b-974e-4093963c9ce1">

**Closed** 2023-07-05 21:01 UTC
Labels: enhancement, user-experience
