### ISSUE TITLE
[multistage] IS NULL/ IS NOT NULL getting skipped from the queries using multistage

### ISSUE THREAD

**Issue by abhioncbr** [apache/pinot#11691] opened 2023-09-27 00:03 UTC
Explain query results for the case/when transformation function based on NULL value comparison shows skipping of the transformation function. For example

```bash
EXPLAIN PLAN FOR SELECT CASE WHEN ArrTimeBlk IS NOT NULL THEN 'null11' ELSE ArrTimeBlk END AS val FROM airlineStats 

Execution Plan
LogicalProject(val=['null11':VARCHAR])
  LogicalTableScan(table=[[airlineStats]])
```

another example

```bash
EXPLAIN PLAN FOR SELECT CASE WHEN ArrTimeBlk IS NULL THEN 'null11' ELSE ArrTimeBlk END AS val FROM airlineStats 

Execution Plan
LogicalProject(val=[$10])
  LogicalTableScan(table=[[airlineStats]])

```

`Where` clause based query

```bash
EXPLAIN PLAN FOR SELECT ArrTimeBlk FROM airlineStats where ArrTimeBlk is not null
Execution Plan
LogicalProject(ArrTimeBlk=[$10])
  LogicalTableScan(table=[[airlineStats]])

EXPLAIN PLAN FOR SELECT ArrTimeBlk FROM airlineStats where ArrTimeBlk is null
Execution Plan
LogicalValues(tuples=[[]])
```

Using docker pinot:1.0.0 release image

**Comment by Jackie-Jiang** [comment] 2023-09-27 00:45
This is a known issue. Currently in multi-stage engine column is registered as non-null, so `IS NULL` and `IS NOT NULL` are just short circuited. We are considering adding `nullable` into `FieldSpec` which can be picked by multi-stage engine to register the column.
cc @walterddr

**Comment by walterddr** [comment] 2023-09-27 02:07
:+1: on @Jackie-Jiang 's point. we already have a pending review PR for this for a long time:
https://github.com/apache/pinot/pull/10423 

however there are debates regarding how to handle configs, how to handle mis-configured scenarios and more; we will likely come up with a better design soon to address this

**Comment by walterddr** [comment] 2023-09-27 02:08
CC @ankitsultana who also worked on #10423, #10381

**Comment by walterddr** [comment] 2023-09-28 20:43
closing this as duplicate of #10381

**Closed by walterddr** 2023-09-28 20:43 UTC
Labels: bug, multi-stage
