### ISSUE TITLE
MergeRollupMinionClusterIntegrationTest is flaky

### ISSUE THREAD

**Issue by richardstartin** [apache/pinot#8218] opened 2022-02-17 17:39 UTC
https://github.com/apache/pinot/runs/5234008775?check_suite_focus=true

**Comment by Jackie-Jiang** [comment] 2022-02-17 18:18
I have seen multiple integration test failures caused by `uploadSegment()`, so we might want to check that. That is common for all integration tests

**Comment by Jackie-Jiang** [comment] 2022-05-10 23:23
The root cause is the same as #8265. Closing this one

**Closed by Jackie-Jiang** 2022-05-10 23:23 UTC
Labels: flaky-test, merge-rollup
