### ISSUE TITLE
OfflineClusterIntegrationTest.testInvertedIndexTriggering is flaky 

### ISSUE THREAD

**Issue by richardstartin** [apache/pinot#8222] opened 2022-02-18 00:14 UTC
https://github.com/apache/pinot/runs/5240101919?check_suite_focus=true

**Comment by Jackie-Jiang** [comment] 2022-05-10 23:59
@klsince Please take a look at this test and see if it still applies

**Comment by klsince** [comment] 2022-05-11 00:17
will look

**Comment by klsince** [comment] 2022-05-11 23:55
not able to reproduce failure on my local; and didn't spot this test case being flaky recently. but lemme know if you've noticed any recent failure on this test case.

**Comment by klsince** [comment] 2022-05-16 17:32
sampled a few recently failed PR builds, and didn't find this test failed the build. I'm closing this for now.

**Comment by richardstartin** [comment] 2022-05-16 17:54
I encountered this today!

**Comment by Jackie-Jiang** [comment] 2022-05-16 22:44
I think this is due to the iteration order of the hash map. @richardstartin Do you run into this locally or in Github Actions? Can you post the link here if there is one?

**Comment by richardstartin** [comment] 2022-05-17 08:04
https://github.com/apache/pinot/runs/6453127269?check_suite_focus=true#step:5:30195

**Comment by klsince** [comment] 2022-05-19 20:13
tried this: https://github.com/apache/pinot/pull/8739

**Comment by Jackie-Jiang** [comment] 2022-05-31 00:14
Got another failure after the fix: https://github.com/apache/pinot/runs/6660284410?check_suite_focus=true

**Comment by klsince** [comment] 2022-05-31 16:53
looking via this debug PR: https://github.com/apache/pinot/pull/8807

**Comment by KKcorps** [comment] 2022-06-07 06:57
Still Flaky. [Happened on PR ](https://github.com/apache/pinot/runs/6754124273?check_suite_focus=true)

**Comment by klsince** [comment] 2022-06-07 18:52
Some quick findings: 

from the error msg, (will add segment name in the error msg)
```
java.lang.AssertionError: Table size: 20900902 should increase after adding inverted index, as compared with 20937551 expected [true] but found [false]
```

But as on my local, the table size is expected be 20949859. 

The gap (48957) between 20949859 and 20900902 was like missing a metadata.properties file. Some segments have `metadata.properties` as 48956 or 48956. 

```
ls -l ... mytable_OFFLINE/mytable_16071_16101_3 %/v3:
total 3472
-rw-r--r--  1 xiaobing  staff  1706093 Jun  7 11:40 columns.psf
-rw-r--r--  1 xiaobing  staff       16 Jun  7 11:40 creation.meta
-rw-r--r--  1 xiaobing  staff    13278 Jun  7 11:40 index_map
-rw-r--r--  1 xiaobing  staff    48956 Jun  7 11:40 metadata.properties


ls -l .../mytable_OFFLINE/mytable_16405_16435_2 %/v3:
total 3336
-rw-r--r--  1 xiaobing  staff  1637322 Jun  7 11:40 columns.psf
-rw-r--r--  1 xiaobing  staff       16 Jun  7 11:39 creation.meta
-rw-r--r--  1 xiaobing  staff    13290 Jun  7 11:40 index_map
-rw-r--r--  1 xiaobing  staff    48957 Jun  7 11:40 metadata.properties
```

**Comment by klsince** [comment] 2022-06-07 18:53
I'll wait for my luck to see this failure again: https://github.com/apache/pinot/pull/8853

**Comment by Jackie-Jiang** [comment] 2022-09-21 05:39
Another failure: https://github.com/apache/pinot/actions/runs/3094335423/jobs/5007603397

**Comment by Jackie-Jiang** [comment] 2023-11-14 22:49
Haven't run into this for 1 year. Close it

**Closed by Jackie-Jiang** 2023-11-14 22:49 UTC
Labels: flaky-test, inverted-index
