### ISSUE TITLE
Issues with recent changes on upload segment endpoint

### ISSUE THREAD

**Issue by sajjad-moradi** [apache/pinot#6966] opened 2021-05-24 23:31 UTC
The changes introduced in this [PR](https://github.com/apache/incubator-pinot/pull/6567/files#diff-d0a60155908b7919915de944c49dfad57e2e5e1cc7ad2988176ac090e57567d7R299) caused the following problem for Refresh use cases in LinkedIn:
- The segment directory in deep store is changed from `tableName/segmentName` to `tableName_OFFLINE/segmentName`. This means that for refresh use cases, the new segments will go to `tableName_OFFLINE` directory, but the older version of the same segment will remain undeleted in `tableName` directory. This is problematic because the older versions need to be manually deleted and now they need extra storage.

Also by just looking at the code, we believe SegmentDeletionManager cannot function properly as it uses rawTableName to construct the uri for the segments to be deleted (details [here](https://github.com/apache/incubator-pinot/blob/master/pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/SegmentDeletionManager.java#L179)).

Please note that with current code, here's the state of the deep store:
- the realtime segments pushed from RT servers use a separate API and then finally reside in `tableName/segmentName` directory.
- the realtime segments for upsert use cases will land in `tableName_REALTIME/segmentName` directory.
- the offline segments will land in `tableName_OFFLINE/segmentName` directory.

**Comment by Jackie-Jiang** [comment] 2021-05-25 00:03
I believe the problem is on `PinotSegmentUploadDownloadRestletResource` line 295 where `tableNameWithType` is mistakenly passed to the `getZkDownloadURIForSegmentUpload()` where `rawTableName` is expected.

Since this PR has been merged for more than 1 months, should we consider changing the behavior to use `tableNameWithType` in the segment path, or revert it back to the old behavior of using `rawTableName`?

The advantage of using `tableNameWithType` in the segment path is to separate the segments for offline and realtime, and allow same segment name for offline and realtime table (might not be desired though). But this is changing the existing behavior, and might cause other classes to not work properly (such as `SegmentDeletionManager` mentioned above)

**Comment by mcvsubbu** [comment] 2021-05-25 01:13
> I believe the problem is on `PinotSegmentUploadDownloadRestletResource` line 295 where `tableNameWithType` is mistakenly passed to the `getZkDownloadURIForSegmentUpload()` where `rawTableName` is expected.
> 
> Since this PR has been merged for more than 1 months, should we consider changing the behavior to use `tableNameWithType` in the segment path, or revert it back to the old behavior of using `rawTableName`?
> 
> The advantage of using `tableNameWithType` in the segment path is to separate the segments for offline and realtime, and allow same segment name for offline and realtime table (might not be desired though). But this is changing the existing behavior, and might cause other classes to not work properly (such as `SegmentDeletionManager` mentioned above)

Exactly. We should fix the controller to do the right thing -- drop the segment in the right place. Otherwise, we open up to other issues that may only surface much later, making production systems take a huge repair time. Right now, the only thing we could find is retention (the new segments uploaded will not get retained out).  But there is no saying what else is out there.

**Comment by chenboat** [comment] 2021-05-25 01:17
The current issue seems to me is primarily about data deletion. We can first patch the SegmentDeletionManager so that it can deal with segments in both types of paths (with type or without). After that we can revert back to the old behavior of using rawTableName.

**Comment by mcvsubbu** [comment] 2021-05-25 01:50
> The current issue seems to me is primarily about data deletion. We can first patch the SegmentDeletionManager so that it can deal with segments in both types of paths (with type or without). After that we can revert back to the old behavior of using rawTableName.

We are seeing production problems with storage, so the best way to move forward is to fix the bleeding and then repair (in the background) what is broken. Please coordinate with @sajjad-moradi  to fix so that upload goes to the right place, and then we can discuss (and add to this issue) how other installations can repair their systems.

**Comment by sajjad-moradi** [comment] 2021-05-25 01:50
@chenboat: I believe it's a safer bet to directly aim for reverting back to the previous directory structure. This way we prevent any potential issues that's not yet discovered. Also if we change SegmentDeletionManager now for cleaning segments in both paths, we later need to make another change once the directory structure is restored to the old way.

**Comment by chenboat** [comment] 2021-05-25 03:47
I suppose there is already some offline table segments being pushed to _tableName_OFFLINE/segmentName_ dir. Do you need to clean them? Or you have other manual means to clean them? If you want to clean them using Pinot services, I proposed to have the SegmentDeletionManager to delete the extra dir's segments as well. Otherwise, yes I agree we can reverting to the old directory layout.

**Comment by sajjad-moradi** [comment] 2021-05-25 16:13
AFAIK SegmentDeletionManager is used for deleting active segments that need to be deleted because of their retention time. Other than retention issue, there's another problem. For refresh use cases, the new segments go to tableName_OFFLINE/segmentName dir, but the older version remain undeleted under tableName/segmentName dir. This exact issue also exists in case of purge task. The purged segments go to the new directory, while the non-purged version of the same segments remain under old directory.

**Closed** 2022-05-23 19:20 UTC
