### ISSUE TITLE
double NaN as default value can massivly expand off heap mutable dictionary

### ISSUE THREAD

**Issue by jvenant** [apache/pinot#10697] opened 2023-04-27 21:21 UTC
Hi,

It seems that using NaN as a default value for Double in schemas can lead to much more calls to the BaseOffHeapMutableDictionary.expand that required.

And because a multiplication factor is apply at each call. It can quickly try to allocate a huge amount of off heap memory
I suspect a hazardous conversion of NaN Double to null somewhere that prevent the DoubleOffHeapMutableDictionary.compare to achieve its goal correctly
I wasn't able to get much more details, but maybe be it will be enough to ring a bell to someone knowing this part of Pinot.

**Comment by Jackie-Jiang** [comment] 2023-04-27 22:26
Good catch. The problem is from `DoubleOffHeapMutableDictionary.equalsValueAt()` which will always return `false` when input `value` is `NaN`.
We can fix it by comparing the `Double.doubleToLongBits()` (bytes level same), but I'm not sure if allowing `NaN` can cause other problems (it might break the binary search as well). Another option is to prevent `NaN` to be ingested (not allowing it as default value, and also replace it with default value when seeing it in the input data)

**Comment by jvenant** [comment] 2023-04-28 07:13
Maybe a quick fix would be to disable NaN.
But from my standpoint, to be able to use NaN would be a better solution as it is not semantically equivalent to Infinities, null or zero. It is a very common value used in mathematical and finance domains.
The only other place where we have issue with NaN so far is in the where filters. We have to do something like : `cast(num_col as STRING) = 'NaN'`. 
`num_col = 'NaN'`, `num_col != 'NaN'` run, but doesn't filter the records correctly

**Comment by jvenant** [comment] 2023-09-20 17:55
I think this bug can be very dangerous. Maybe waiting for a good NaN management, we could reject schemas in case on NaN default...?

**Comment by Jackie-Jiang** [comment] 2023-09-21 02:32
I feel we should just reject `NaN` for now. Dictionary binary search might also fail.
To reject it, we can add a check in `FieldSpec.getDefaultNullValue()`, and in the record reader, replace `NaN` with the default value. @jvenant Do you want to help contribute this?

cc @snleee

**Comment by jvenant** [comment] 2023-09-26 18:59
Not sure the PR actually fix the issue. It's more a protection than a fix

**Comment by Jackie-Jiang** [comment] 2023-09-26 19:02
It is auto-closed by merging #11661. Reopened it since we haven't addressed the issue completely

**Comment by snleee** [comment] 2023-10-14 03:42
MySQL: not allow `NaN`
Postgres: allow `NaN` 
official documentation states, `In order to allow numeric values to be sorted and used in tree-based indexes, PostgreSQL treats NaN values as equal, and greater than all non-NaN values.`

Some similar issue with `-0.0` and `0.0` (This would also mess up the binary search/sorting)
https://jonisalonen.com/2013/positive-and-negative-zeros-and-mysql/

**Comment by Jackie-Jiang** [comment] 2023-10-14 08:10
To simplify the handling, as a short term solution, I'd propose:
- Not allowing `NaN` and replace it with default null value when ingested
- Replacing `-0.0` with `0.0`

We may consider following PostgreSQL behavior as long term solution

**Comment by snleee** [comment] 2023-10-18 17:25
@Jackie-Jiang sounds good to me.

**Comment by hpvd** [comment] 2024-06-15 21:50
@Jackie-Jiang since now also the second bugfix is merged: can this issue be closed or do we keep it open till `PostgreSQL behavior` is implemented?

**Closed** 2024-06-16 18:05 UTC
Labels: bug
