### ISSUE TITLE
Jackson infinite recursion error (unnested fields)

### ISSUE THREAD

**Issue by Airliquide76** [apache/pinot#8549] opened 2022-04-15 12:49 UTC
I face an error linked to cols name I think.

Version used 10.0.0 

When I set a filter config with the folowing schema part :

`    "filterConfig":{
            "filterFunction": "Groovy({exceptionaltime.id != null })"
          },`

I've got a hudge shaded.com.fasterxml.jackson.databind  infinited loop see attached logs bellow. 

[Githubissue.txt](https://github.com/apache/pinot/files/8495947/Githubissue.txt)

When I remove the filter config docs get correctly indexed. 

I've face the same issue (without the filterConfig) with Pre-PROD serveur V9.3.0 with same schema and table config. Working 
in local (10.0.0) not working in V9.3.0 

Do not hesitate to ask further question and sorry for my poor english.

**Comment by npawar** [comment] 2022-04-18 16:34
On the slack thread, you mentioned you're using complexTypeConfig? Do you mind sharing the table config, the pinot schema and a sample row that fails?

**Comment by Airliquide76** [comment] 2022-04-19 08:31
Hi. As asked a few more informations :

[regulartimes-schema.txt](https://github.com/apache/pinot/files/8511219/regulartimes-schema.txt)
[regulartimes-table.txt](https://github.com/apache/pinot/files/8511220/regulartimes-table.txt)

This schema is actualy working. But as soon as I add 

`"filterConfig":{ "filterFunction": "Groovy({regulartime.id != null })" },` -> It crash.

Here a sample of a few rows. 
[SampleRow.txt](https://github.com/apache/pinot/files/8511297/SampleRow.txt)

**Comment by saumya2700** [comment] 2022-04-20 13:13
I am also getting the same exception using FiledTounnest configuration, I am not using any filterconfig still getting recursion error.

**Comment by npawar** [comment] 2022-04-21 02:48
@Airliquide76 I couldn't reproduce the recursion issue, I tried with 0.10.0 and also with master.

If you're good with 0.10.0, then the only issue is with the filterConfig, and for that, the problem is that Groovy doesn't like "." in variable names. So you'll have to change the name of "regulartime.id" to something else. This is what worked for me:
```
"filterConfig":{ "filterFunction": "Groovy({regulartimeId == null }, regulartimeId)" },
```
and for this I had to change in schema too 
```
   {
      "dataType": "STRING",
      "name": "regulartimeId",
      "singleValueField": true
    },
```
and also in table config
```
{
      "columnName": "regulartimeId",
      "transformFunction": "\"data.attributes.regularTimes.id\""
    },
```

**Comment by npawar** [comment] 2022-04-21 02:49
@saumya2700 which version are you using? Can you try with 0.10.0 if you're using something older?

**Comment by saumya2700** [comment] 2022-04-21 04:37
I am using 0.10.0 v also one more observation this error start coming after some time when I have created table it is ingesting data for 2,3 days and it has around 45K data in it but after that due to this error everything stopped means all segments in external view are also in offline state. I gaian created same table config with different name and it started working and ingesting data but not sure when this problem will come and it will stop working.

**Comment by saumya2700** [comment] 2022-04-21 05:39
I am attaching schema , table and data
[recursionISsueSampleDataandSchema.txt](https://github.com/apache/pinot/files/8527601/recursionISsueSampleDataandSchema.txt)

**Comment by saumya2700** [comment] 2022-04-21 06:07
here is sample table, schema and sample data.
[Uploading recursionISsueSampleDataandSchema.txt…]()

**Comment by Airliquide76** [comment] 2022-04-25 12:20
Well issue was really linked with the groovy witch does not like the "." in my side.

For me this issue can be closed.

Many thanks

**Comment by Jackie-Jiang** [comment] 2022-04-26 20:50
Closing the issue.
@saumya2700 The exception you got is from flattening the docs, so it is under a different topic. If the problem is still not resolved, could you please create a separate issue?

**Closed by Jackie-Jiang** 2022-04-26 20:50 UTC
